spring:  application:    name: StaticModule  jpa:    hibernate:      ddl-auto: updateserver:  port: 8082 eureka:  client:    register-with-eureka: true    fetch-registry: true    service-url:       defaultZone: https://eurekaserverfdx.cfapps.io/eureka#      defaultZone: http://localhost:8761/eureka  

